# Generated by Django 4.1.5 on 2023-01-27 08:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='blog title', max_length=50, unique=True, verbose_name='Blog title')),
                ('body', models.TextField(unique=True, verbose_name='Blog body')),
                ('date', models.DateTimeField(auto_now=True)),
                ('num_stars', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Blog Category')),
            ],
        ),
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Nigeria', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Federal_Constituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lga', max_length=50)),
                ('fedCon', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='senDis', chained_model_field='senDis', on_delete=django.db.models.deletion.CASCADE, to='accounts.federal_constituent')),
            ],
        ),
        migrations.CreateModel(
            name='Manifestoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestoe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sector', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Senatorial_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('federal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.federal')),
                ('name', models.CharField(default='state', max_length=10, unique=True)),
            ],
            bases=('accounts.federal',),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ward', max_length=20)),
                ('fedCon', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='senDis', chained_model_field='senDis', on_delete=django.db.models.deletion.CASCADE, to='accounts.federal_constituent')),
                ('lga', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fedCon', chained_model_field='fedCon', on_delete=django.db.models.deletion.CASCADE, to='accounts.lga')),
                ('senDis', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='accounts.senatorial_district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_lga_state', to='accounts.state')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('phone_number', models.IntegerField(default='+234')),
                ('fedCon', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='senDis', chained_model_field='senDis', on_delete=django.db.models.deletion.CASCADE, to='accounts.federal_constituent')),
                ('lga', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='fedCon', chained_model_field='fedCon', on_delete=django.db.models.deletion.CASCADE, to='accounts.lga')),
                ('senDis', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='accounts.senatorial_district')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lga', chained_model_field='lga', on_delete=django.db.models.deletion.CASCADE, to='accounts.ward')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_state', to='accounts.state')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Senatorial_districtPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('has_voted', models.BooleanField(default=True)),
                ('manifestoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_senatorial_district_poll', to='accounts.manifestoe')),
                ('senatorial_district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='voter', chained_model_field='state_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.senatorial_district')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senatorial_district_voter', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_checked_date', models.DateTimeField(auto_now=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_user_result', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='manifestoe',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_sector', to='accounts.sector'),
        ),
        migrations.CreateModel(
            name='LGAPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('has_voted', models.BooleanField(default=True)),
                ('lga', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='voter', chained_model_field='user', on_delete=django.db.models.deletion.CASCADE, to='accounts.lga')),
                ('manifestoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_lga_poll', to='accounts.manifestoe')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_voter', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='senDis',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='accounts.senatorial_district'),
        ),
        migrations.CreateModel(
            name='FederalPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('has_voted', models.BooleanField(default=True)),
                ('manifestoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_federal_poll', to='accounts.manifestoe')),
            ],
        ),
        migrations.CreateModel(
            name='Federal_ConstituentPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('has_voted', models.BooleanField(default=True)),
                ('manifestoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_federal_const_poll', to='accounts.manifestoe')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Federal_Constituent_voter', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='federal_constituent',
            name='senDis',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='accounts.senatorial_district'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloga', to='accounts.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
        migrations.CreateModel(
            name='StatePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('vote_date', models.DateTimeField(auto_now=True)),
                ('has_voted', models.BooleanField(default=True)),
                ('manifestoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestoe_state_poll', to='accounts.manifestoe')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_voter', to='accounts.user')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='voter', chained_model_field='user_state', on_delete=django.db.models.deletion.CASCADE, to='accounts.state')),
            ],
        ),
        migrations.AddField(
            model_name='senatorial_district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendistrict_state', to='accounts.state'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga_state', to='accounts.state'),
        ),
        migrations.AddField(
            model_name='federal_constituent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Federal_Constituent_state', to='accounts.state'),
        ),
    ]
