


states = {'AB': {'stateAbbr': 'AB',
                       #'alpha3': 'ABW',
                       'area_km': 193,
                       'area_miles': 75,
                       'area_ranking': 220,
                       'capital': 'Umuahia',
                       'region': 'SOUTH_EAST',
                       #'flag_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/1920px-Flag_of_Aruba.svg.png',
                       'gdp': 3293000000,
                       'gdp_per_capita': 30662,
                       'gdp_per_capita_ranking': 56,
                       'gdp_ranking': 178,
                       'largest_city': 'Aba',
                       'name': 'Abia',
                       'population': 107394,
                       'population_density_km': 556.45,
                       'population_density_miles': 1431.92,
                       'population_density_ranking': 21,
                       'population_ranking': 194},
                       'government': 'Abia State Government',
                       'senatorial_district': [
                            'Abia North',
                            'Abia Central',
                            'Abia South'],
                        'federal_constituencies': []
                        'lgas': [
                                  "Aba North",
                                  "Arochukwu",
                                  "Aba South",
                                  "Bende",
                                  "Isiala Ngwa North",
                                  "Ikwuano",
                                  "Isiala Ngwa South",
                                  "Isuikwuato",
                                  "Obi Ngwa",
                                  "Ohafia",
                                  "Osisioma",
                                  "Ugwunagbo",
                                  "Ukwa East",
                                  "Ukwa West",
                                  "Umuahia North",
                                  "Umuahia South",
                                  "Umu Nneochi"],
                        'state_constituencies': [],
                        'wards': [],
                        'communities': [],
                        'mineral_resources': [],
                        'languages':[],
                        'ethnic_groups':[],
                        'average_temperature':[],
                        'rice_qty_produce_annually': 11111,
                        'beans_qty_in_tonnes_annually': 222222,
                        'yam_tubers_in_tonnes_annually':888888,
                        'garri': 888888,
                        ''
                        'food_sufficiency_ranking': [],
                        

                       
        'AD': {'stateAbbr': 'AD',
                       #'alpha3': 'AFG',
                       'area_km': 652230,
                       'area_miles': 251827,
                       'area_ranking': 41,
                       'capital': 'Yola',
                       'region': 'NORTH_EAST',
                       #'flag_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/2560px-Flag_of_the_Taliban.svg.png',
                       'gdp': 17876000000,
                       'gdp_per_capita': 646,
                       'gdp_per_capita_ranking': 229,
                       'gdp_ranking': 121,
                       'largest_city': 'Yola',
                       'name': 'Adamawa',
                       #'official_name': 'Islamic Republic of Afghanistan',
                       'population': 27657145,
                       'population_density_km': 42.4,
                       'population_density_miles': 109.83,
                       'population_density_ranking': 170,
                       'population_ranking': 46},
                       
            'AK': {'stateAbbr': 'AK',
                       #'alpha3': 'AGO',
                       'area_km': 1246700,
                       'area_miles': 481352,
                       'area_ranking': 23,
                       'capital': 'Uyo',
                       'region': 'SOUTH_SOUTH',
                       #'flag_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/1280px-Flag_of_Angola.svg.png',
                       'gdp': 85000000000,
                       'gdp_per_capita': 3285,
                       'gdp_per_capita_ranking': 181,
                       'gdp_ranking': 69,
                       'largest_city': 'Uyo',
                       'name': 'Akwa Ibom',
                       'population': 25868000,
                       'population_density_km': 20.75,
                       'population_density_miles': 53.74,
                       'population_density_ranking': 195,
                       'population_ranking': 49},