

NIG_LGAS = (
    ('Abia',(
        ('1', 'Aba North'),
        ('2', 'Aba South'),
        ('3', 'Arochukwu'),
        ('4', 'Ohafia'),
        ('5', 'Bende'),
        ('6','Isiala Ngwa North'),
        ('7','Isiala Ngwa South'),
        ('8','Isuikwuato'),
        ('9','Umu-Nneochi'),
        ('10','Obingwa'),
        ('11', 'Ugwunagbo'),
        ('12','Osisioma'),
        ('13','Umuahia North'),
        ('14','Umuahia South'),
        ('15','Ikwuano'),
        ('16','Ukwa East'),
        ('17','Ukwa West'),
        ),
    
    ),
    ('Adamawa',(
        ('18',"Demsa"),
        ('19',"Fufure"),
        ('20',"Ganye"),
        ('21',"Gayuk"),
        ('22',"Gombi"),
        ('23',"Grie"),
        ('24',"Hong"),
        ('25',"Jada"),
        ('26',"Larmurde"),
        ('27',"Madagali"),
        ('28',"Maiha"),
        ('29',"Mayo Belwa"),
        ('30',"Michika"),
        ('31',"Mubi North"),
        ('32',"Mubi South"),
        ('33',"Numan"),
        ('34',"Shelleng"),
        ('35',"Song"),
        ('36',"Toungo"),
        ('37',"Yola North"),
        ('38',"Yola South"),
        )
    ),
    ('Akwa Ibom',(
        ('39',"Abak"),
        ('40',"Eastern Obolo"),
        ('41',"Eket"),
        ('42',"Esit Eket"),
        ('43',"Essien Udim"),
        ('44',"Etim Ekpo"),
        ('45',"Etinan"),
        ('46',"Ibeno"),
        ('47',"Ibesikpo Asutan"),
        ('48',"Ibiono-Ibom"),
        ('49',"Ikot Abasi"),
        ('50',"Ika"),
        ('51',"Ikono"),
        ('52',"Ikot Ekpene"),
        ('53',"Ini"),
        ('54',"Mkpat-Enin"),
        ('55',"Itu"),
        ('56',"Mbo"),
        ('57',"Nsit-Atai"),
        ('58',"Nsit-Ibom"),
        ('59',"Nsit-Ubium"),
        ('60',"Obot Akara"),
        ('61',"Okobo"),
        ('62',"Onna"),
        ('63',"Oron"),
        ('64',"Udung-Uko"),
        ('65',"Ukanafun"),
        ('66',"Oruk Anam"),
        ('67',"Uruan"),
        ('68',"Urue-Offong/Oruko"),
        ('69',"Uyo"),
        )
    ),
    ("Anambra",(
        ('70',"Aguata"),
        ('71',"Anambra East"),
        ('72',"Anaocha"),
        ('73',"Awka North"),
        ('74',"Anambra West"),
        ('75',"Awka South"),
        ('76',"Ayamelum"),
        ('77',"Dunukofia"),
        ('78',"Ekwusigo"),
        ('79',"Idemili North"),
        ('80',"Idemili South"),
        ('81',"Ihiala"),
        ('82',"Njikoka"),
        ('83',"Nnewi North"),
        ('84',"Nnewi South"),
        ('85',"Ogbaru"),
        ('86',"Onitsha North"),
        ('87',"Onitsha South"),
        ('88',"Orumba North"),
        ('89',"Orumba South"),
        ('90',"Oyi"),
        ),
    ),
    ('Bauchi',(
        ('91',"Alkaleri"),
        ('92',"Bauchi"),
        ('93',"Bogoro"),
        ('94',"Damban"),
        ('95',"Darazo"),
        ('96',"Dass"),
        ('97',"Gamawa"),
        ('98',"Ganjuwa"),
        ('99',"Giade"),
        ('100',"Itas/Gadau"),
        ('101',"Jama'are"),
        ('102',"Katagum"),
        ('103',"Kirfi"),
        ('104',"Misau"),
        ('105',"Ningi"),
        ('106',"Shira"),
        ('107',"Tafawa Balewa"),
        ('108',"Toro"),
        ('109',"Warji"),
        ('110',"Zaki"),
        ),
    ),
    ('Bayelsa',(
        ('111',"Brass"),
        ('112',"Ekeremor"),
        ('113',"Kolokuma/Opokuma"),
        ('114',"Nembe"),
        ('115',"Ogbia"),
        ('116',"Sagbama"),
        ('117',"Southern Ijaw"),
        ('118',"Yenagoa"),
        ),
    ),
    ('Benue',(
        ('119',"Agatu"),
        ('120',"Apa"),
        ('121',"Ado"),
        ('122',"Buruku"),
        ('123',"Gboko"),
        ('124',"Guma"),
        ('125',"Gwer East"),
        ('126',"Gwer West"),
        ('127',"Katsina-Ala"),
        ('128',"Konshisha"),
        ('129',"Kwande"),
        ('130',"Logo"),
        ('131',"Makurdi"),
        ('132',"Obi"),
        ('133',"Ogbadibo"),
        ('134',"Ohimini"),
        ('135',"Oju"),
        ('136',"Okpokwu"),
        ('137',"Oturkpo"),
        ('138',"Tarka"),
        ('139',"Ukum"),
        ('140',"Ushongo"),
        ('141',"Vandeikya"),
        ),
    ),
    ('Borno',(
        ('142',"Abadam"),
        ('143',"Askira/Uba"),
        ('144',"Bama"),
        ('145',"Bayo"),
        ('146',"Biu"),
        ('147',"Chibok"),
        ('148',"Damboa"),
        ('149',"Dikwa"),
        ('150',"Guzamala"),
        ('151',"Gubio"),
        ('152',"Hawul"),
        ('153',"Gwoza"),
        ('154',"Jere"),
        ('155',"Kaga"),
        ('156',"Kala/Balge"),
        ('157',"Konduga"),
        ('158',"Kukawa"),
        ('159',"Kwaya Kusar"),
        ('160',"Mafa"),
        ('161',"Magumeri"),
        ('162',"Maiduguri"),
        ('163',"Mobbar"),
        ('164',"Marte"),
        ('165',"Monguno"),
        ('166',"Ngala"),
        ('167',"Nganzai"),
        ('168',"Shani"),
        ),
    ),
    ('Cross River',(
        ('169',"Abi"),
        ('170',"Akamkpa"),
        ('171',"Akpabuyo"),
        ('172',"Bakassi"),
        ('173',"Bekwarra"),
        ('174',"Biase"),
        ('175',"Boki"),
        ('176',"Calabar Municipal"),
        ('177',"Calabar South"),
        ('178',"Etung"),
        ('179',"Ikom"),
        ('180',"Obanliku"),
        ('181',"Obubra"),
        ('182',"Obudu"),
        ('183',"Odukpani"),
        ('184',"Ogoja"),
        ('185',"Yakuur"),
        ('186',"Yala"),
        ),
    ),
    ('Delta',(
        ('187',"Aniocha North"),
        ('188',"Aniocha South"),
        ('189',"Bomadi"),
        ('190',"Burutu"),
        ('191',"Ethiope West"),
        ('192',"Ethiope East"),
        ('193',"Ika North East"),
        ('194',"Ika South"),
        ('195',"Isoko North"),
        ('196',"Isoko South"),
        ('197',"Ndokwa East"),
        ('198',"Ndokwa West"),
        ('199',"Okpe"),
        ('200',"Oshimili North"),
        ('201',"Oshimili South"),
        ('202',"Patani"),
        ('203',"Sapele"),
        ('204',"Udu"),
        ('205',"Ughelli North"),
        ('206',"Ukwuani"),
        ('207',"Ughelli South"),
        ('208',"Uvwie"),
        ('209',"Warri North"),
        ('210',"Warri South"),
        ('211',"Warri South West"),
        ),
    ),
    ("Ebonyi",(
        ('212',"Abakaliki"),
        ('213',"Afikpo North"),
        ('214',"Ebonyi"),
        ('215',"Afikpo South"),
        ('216',"Ezza North"),
        ('217',"Ikwo"),
        ('218',"Ezza South"),
        ('219',"Ivo"),
        ('220',"Ishielu"),
        ('221',"Izzi"),
        ('222',"Ohaozara"),
        ('223',"Ohaukwu"),
        ('224',"Onicha"),
        ),
    ),
    ('Edo',(
        ('225','Akoko-Edo'),
        ('226', 'Esan Central'),
        ('227', 'Esan North East'),
        ('228', 'Esan South East'),
        ('229','Esan West'),
        ('230', 'Etsako Central'),
        ('231', 'Etsako East'),
        ('232', 'Etsako West'),
        ('233', 'Egor'),
        ('234', 'Ikpoba-Okha'),
        ('235', 'Igueben'),
        ('236', 'Oredo'),
        ('237', 'Orhionmwon'),
        ('238', 'Ovia North East'),
        ('239', 'Ovia South West'),
        ('240', 'Owan East'),
        ('241', 'Owan West'),
        ('242', 'Uhunmwode'),
        ),
    ),
    ('Ekiti',(
        ('243',"Ado Ekiti"),
        ('244',"Efon"),
        ('245',"Ekiti East"),
        ('246',"Ekiti South-West"),
        ('247',"Ekiti West"),
        ('248',"Emure"),
        ('249',"Gbonyin"),
        ('250',"Ido Osi"),
        ('251',"Ijero"),
        ('252',"Ikere"),
        ('253',"Ilejemeje"),
        ('254',"Irepodun/Ifelodun"),
        ('255',"Ikole"),
        ('256',"Ise/Orun"),
        ('257',"Moba"),
        ('258',"Oye"),
        ),
    ),
    ('Enugu',(
        ('259',"Awgu"),
        ('260',"Aninri"),
        ('261',"Enugu East"),
        ('262',"Enugu North"),
        ('263',"Ezeagu"),
        ('264',"Enugu South"),
        ('265',"Igbo Etiti"),
        ('267',"Igbo Eze North"),
        ('268',"Igbo Eze South"),
        ('269',"Isi Uzo"),
        ('270',"Nkanu East"),
        ('271',"Nkanu West"),
        ('272',"Nsukka"),
        ('273',"Udenu"),
        ('274',"Oji River"),
        ('275',"Uzo Uwani"),
        ('276',"Udi"),
        ),
    ),
    ('Gombe',(
        ('277',"Akko"),
        ('278',"Balanga"),
        ('279',"Billiri"),
        ('280',"Dukku"),
        ('281',"Funakaye"),
        ('282',"Gombe"),
        ('283',"Kaltungo"),
        ('284',"Kwami"),
        ('285',"Nafada"),
        ('286',"Shongom"),
        ('287',"Yamaltu/Deba"),
        ),
    ),
    ('Imo',(
        ('288',"Aboh Mbaise"),
        ('289',"Ahiazu Mbaise"),
        ('290',"Ehime Mbano"),
        ('291',"Ezinihitte"),
        ('292',"Ideato North"),
        ('293',"Ideato South"),
        ('294',"Ihitte/Uboma"),
        ('295',"Ikeduru"),
        ('296',"Isiala Mbano"),
        ('297',"Mbaitoli"),
        ('298',"Isu"),
        ('299',"Ngor Okpala"),
        ('300',"Njaba"),
        ('301',"Nkwerre"),
        ('302',"Nwangele"),
        ('303',"Obowo"),
        ('304',"Oguta"),
        ('305',"Ohaji/Egbema"),
        ('306',"Okigwe"),
        ('307',"Orlu"),
        ('308',"Orsu"),
        ('309',"Oru East"),
        ('310',"Oru West"),
        ('311',"Owerri Municipal"),
        ('312',"Owerri North"),
        ('313',"Unuimo"),
        ('314',"Owerri West"),
        ),
    ),
    ('Jigawa',(
        ('315',"Auyo"),
        ('316',"Babura"),
        ('317',"Buji"),
        ('318',"Biriniwa"),
        ('319',"Birnin Kudu"),
        ('320',"Dutse"),
        ('321',"Gagarawa"),
        ('322',"Garki"),
        ('323',"Gumel"),
        ('324',"Guri"),
        ('325',"Gwaram"),
        ('326',"Gwiwa"),
        ('327',"Hadejia"),
        ('328',"Jahun"),
        ('329',"Kafin Hausa"),
        ('330',"Kazaure"),
        ('331',"Kiri Kasama"),
        ('332',"Kiyawa"),
        ('333',"Kaugama"),
        ('334',"Maigatari"),
        ('335',"Malam Madori"),
        ('336',"Miga"),
        ('337',"Sule Tankarkar"),
        ('338',"Roni"),
        ('339',"Ringim"),
        ('340',"Yankwashi"),
        ('341',"Taura"),
        ),
    ),
    ("Kaduna",(
        ('342',"Birnin Gwari"),
        ('343',"Chikun"),
        ('345',"Giwa"),
        ('346',"Ikmara"),
        ('347',"Igabi"),
        ('348',"Jaba"),
        ('349',"Jema'a"),
        ('350',"Kachia"),
        ('351',"Kaduna North"),
        ('352',"Kaduna South"),
        ('353',"Kagarko"),
        ('354',"Kajuru"),
        ('355',"Kaura"),
        ('356',"Kauru"),
        ('357',"Kubau"),
        ('358',"Kudan"),
        ('359',"Lere"),
        ('360',"Makarfi"),
        ('361',"Sabon Gari"),
        ('362',"Sanga"),
        ('363',"Soba"),
        ('364',"Zangon Kataf"),
        ('365',"Zaria"),
        ),
    ),
    ('Kano',(
        ('366',"Ajingi"),
        ('367',"Albasu"),
        ('368',"Bagwai"),
        ('369',"Bebeji"),
        ('370',"Bichi"),
        ('371',"Bunkure"),
        ('372',"Dala"),
        ('373',"Dambatta"),
        ('374',"Dawakin Kudu"),
        ('375',"Dawakin Tofa"),
        ('376',"Doguwa"),
        ('377',"Fagge"),
        ('378',"Gabasawa"),
        ('379',"Garko"),
        ('380',"Garun Mallam"),
        ('381',"Gezawa"),
        ('382',"Gaya"),
        ('383',"Gwale"),
        ('384',"Gwarzo"),
        ('385',"Kabo"),
        ('386',"Kano Municipal"),
        ('387',"Karaye"),
        ('388',"Kibiya"),
        ('389',"Kiru"),
        ('390',"Kumbotso"),
        ('391',"Kunchi"),
        ('392',"Kura"),
        ('393',"Madobi"),
        ('394',"Makoda"),
        ('395',"Minjibir"),
        ('396',"Nasarawa"),
        ('397',"Rano"),
        ('398',"Rimin Gado"),
        ('399',"Rogo"),
        ('400',"Shanono"),
        ('401',"Takai"),
        ('402',"Sumaila"),
        ('403',"Tarauni"),
        ('404',"Tofa"),
        ('405',"Tsanyawa"),
        ('406',"Tudun Wada"),
        ('407',"Ungogo"),
        ('408',"Warawa"),
        ('409',"Wudil"),
        ),
    ),
    ('Katsina',(
        ('410',"Bakori"),
        ('411',"Batagarawa"),
        ('412',"Batsari"),
        ('413',"Baure"),
        ('414',"Bindawa"),
        ('415',"Charanchi"),
        ('416',"Danja"),
        ('417',"Dandume"),
        ('418',"Dan Musa"),
        ('419',"Daura"),
        ('420',"Dutsi"),
        ('421',"Dutsin Ma"),
        ('422',"Faskari"),
        ('423',"Funtua"),
        ('424',"Ingawa"),
        ('425',"Jibia"),
        ('426',"Kafur"),
        ('427',"Kaita"),
        ('428',"Kankara"),
        ('429',"Kankia"),
        ('430',"Katsina"),
        ('431',"Kurfi"),
        ('432',"Kusada"),
        ('433',"Mai'Adua"),
        ('434',"Malumfashi"),
        ('435',"Mani"),
        ('436',"Mashi"),
        ('437',"Matazu"),
        ('438',"Musawa"),
        ('439',"Rimi"),
        ('440',"Sabuwa"),
        ('441',"Safana"),
        ('442',"Sandamu"),
        ('443',"Zango"),
        ),
    ),
    # Kebbi
    ('Kogi',(
        ('444',"Ajaokuta"),
        ('445',"Adavi"),
        ('446',"Ankpa"),
        ('447',"Bassa"),
        ('448',"Dekina"),
        ('449',"Ibaji"),
        ('450',"Idah"),
        ('451',"Igalamela Odolu"),
        ('452',"Ijumu"),
        ('453',"Kogi"),
        ('454',"Kabba/Bunu"),
        ('455',"Lokoja"),
        ('456',"Ofu"),
        ('457',"Mopa Muro"),
        ('458',"Ogori/Magongo"),
        ('459',"Okehi"),
        ('460',"Okene"),
        ('461',"Olamaboro"),
        ('462',"Omala"),
        ('463',"Yagba East"),
        ('464',"Yagba West"),
        ),
    ),
    ('Kwara',(
        ('465',"Asa"),
        ('466',"Baruten"),
        ('467',"Edu"),
        ('468',"Ilorin East"),
        ('469',"Ifelodun"),
        ('470',"Ilorin South"),
        ('471',"Ekiti"),
        ('472',"Ilorin West"),
        ('473',"Irepodun"),
        ('474',"Isin"),
        ('475',"Kaiama"),
        ('476',"Moro"),
        ('477',"Offa"),
        ('478',"Oke Ero"),
        ('479',"Oyun"),
        ('480',"Pategi"),
        ),
    ),
    ('Lagos',(
        ('481', 'Alimosho'),
        ('482', 'Ojo'),
        ('483', 'Badagry'),
        ('484', 'Epe'),
        ('485', 'Agege'),
        ('486','Ifako-Ijaiye'),
        ('487','Oshodi-Isolo'),
        ('488','Ibeju Lekki'),
        ('489','Eti-Osa'),
        ('490','Apapa'),
        ('491', 'Ikeja'),
        ('492','Ikorodu'),
        ('493','Lagos Island'),
        ('494','Lagos Mainland'),
        ('495','Amuwo-Odofin'),
        ('496','Ajeromi-Ifelodun'),
        ('497','Shomolu'),
        ('498','Kosofe'),
        ('499','Surulere'),
        ('500','Mushin'),
        ),
    ),
)
    
