

NIG_LGAS = (
    ('Abia',(
        ('1', 'Aba North'),
        ('2', 'Aba South'),
        ('3', 'Arochukwu'),
        ('4', 'Ohafia'),
        ('5', 'Bende'),
        ('6','Isiala Ngwa North'),
        ('7','Isiala Ngwa South'),
        ('8','Isuikwuato'),
        ('9','Umu-Nneochi'),
        ('10','Obingwa'),
        ('11', 'Ugwunagbo'),
        ('12','Osisioma'),
        ('13','Umuahia North'),
        ('14','Umuahia South'),
        ('15','Ikwuano'),
        ('16','Ukwa East'),
        ('17','Ukwa West'),
        ),
    
    ),
    
    ('Edo',(
        ('18','Akoko-Edo'),
        ('19', 'Esan Central'),
        ('20', 'Esan North East'),
        ('21', 'Esan South East'),
        ('22','Esan West'),
        ('23', 'Etsako Central'),
        ('24', 'Etsako East'),
        ('25', 'Etsako West'),
        ('26', 'Egor'),
        ('27', 'Ikpoba-Okha'),
        ('28', 'Igueben'),
        ('29', 'Oredo'),
        ('30', 'Orhionmwon'),
        ('31', 'Ovia North East'),
        ('32', 'Ovia South West'),
        ('33', 'Owan East'),
        ('34', 'Owan West'),
        ('35', 'Uhunmwode'),
        ),
    ),
    
    ('Lagos',(
        ('36', 'Alimosho'),
        ('37', 'Ojo'),
        ('38', 'Badagry'),
        ('39', 'Epe'),
        ('40', 'Agege'),
        ('41','Ifako-Ijaiye'),
        ('42','Oshodi-Isolo'),
        ('43','Ibeju Lekki'),
        ('44','Eti-Osa'),
        ('45','Apapa'),
        ('46', 'Ikeja'),
        ('47','Ikorodu'),
        ('48','Lagos Island'),
        ('49','Lagos Mainland'),
        ('50','Amuwo-Odofin'),
        ('51','Ajeromi-Ifelodun'),
        ('52','Shomolu'),
        ('53','Kosofe'),
        ('54','Surulere'),
        ('55','Mushin'),
        ),
    ),
)
    
