


   
NIG_SENATORIAL_DISTRICTS= (
    
    ('Abia',(
        ('1','Abia South'),
        ('2','Abia Central'),
        ('3','Abia North'),
        ),
    ),
    ('Adamawa',(
        ('4','Adamawa South'),
        ('5','Adamawa Central'),
        ('6','Adamawa North'),
        ),
    ),
    ('Akwa Ibom',(
        ('7','Akwa Ibom East'),
        ('8','Akwa Ibom West'),
        ('9','Akwa Ibom South'),
        ),
    ),
    ('Anambra',(
        ('10','Anambra South'),
        ('11','Anambra Central'),
        ('12','Anambra North'),
        ),
    ),
    ('Bauchi',(
        ('13','Bauchi South'),
        ('14','Bauchi Central'),
        ('15','Bauchi North'),
        ),
    ),
    ('Bayelsa',(
        ('16','Bayelsa East'),
        ('17','Bayelsa Central'),
        ('18','Bayelsa West'),
        ),
    ),
    ('Benue',(
        ('19','Benue East'),
        ('20','Benue West'),
        ('21','Benue South'),
        ),
    ),
    ('Borno',(
        ('22','Borno South'),
        ('23','Borno Central'),
        ('24','Borno North'),
        ),
    ),
    ('Cross River',(
        ('25','Cross River South'),
        ('26','Cross River Central'),
        ('27','Cross River North'),
        ),
    ),
    ('Delta',(
        ('28','Delta South'),
        ('29','Delta Central'),
        ('30','Delta North'),
        ),
    ),
    ('Ebonyi',(
        ('31','Ebonyi South'),
        ('32','Ebonyi Central'),
        ('33','Ebonyi North'),
        ),
    ),
    ('Edo',(
        ('34','Edo South'),
        ('35','Edo Central'),
        ('36','Edo North'),
        ),
    ),
    ('Ekiti',(
        ('37','Ekiti South'),
        ('38','Ekiti Central'),
        ('39','Ekiti North'),
        ),
    ),
    ('Enugu',(
        ('40','Enugu East'),
        ('41','Enugu West'),
        ('42','Enugu North'),
        ),
    ),
    ('Gombe',(
        ('43','Gombe South'),
        ('44','Gombe Central'),
        ('45','Gombe North'),
        ),
    ),
    ('Imo',(
        ('46','Imo East'),
        ('47','Imo West'),
        ('48','Imo North'),
        ),
    ),
    ('Jigawa',(
        ('49','Jigawa North-East'),
        ('50','Jigawa North-West'),
        ('51','Jigawa South-West'),
        ),
    ),
    ('Kaduna',(
        ('52','Kaduna South'),
        ('53','Kaduna Central'),
        ('54','Kaduna North'),
        ),
    ),
    ('Kano',(
        ('55','Kano South'),
        ('56','Kano Central'),
        ('57','Kano North'),
        ),
    ),
    ('Katsina',(
        ('58','Katsina South'),
        ('59','Katsina Central'),
        ('60','Katsina North'),
        ),
    ),
    ('Kebbi',(
        ('61','Kebbi South'),
        ('62','Kebbi Central'),
        ('63','Kebbi North'),
        ),
    ),
    ('Kogi',(
        ('64','Kogi East'),
        ('65','Kogi Central'),
        ('66','Kogi West'),
        ),
    ),
    ('Kwara',(
        ('67','Kwara South'),
        ('68','Kwara Central'),
        ('69','Kwara North'),
        ),
    ),
    ('Lagos',(
        ('70','Lagos East'),
        ('71','Lagos Central'),
        ('72','Lagos West'),
        ),
    ),
    ('Nassarawa',(
        ('73','Nassarawa South'),
        ('74','Nassarawa West'),
        ('75','Nassarawa North'),
        ),
    ),
    ('Niger',(
        ('76','Niger South'),
        ('77','Niger East'),
        ('78','Niger North'),
        ),
    ),
    ('Ogun',(
        ('79','Ogun East'),
        ('80','Ogun Central'),
        ('81','Ogun West'),
        ),
    ),
    ('Ondo',(
        ('82','Ondo South'),
        ('83','Ondo Central'),
        ('84','Ondo North'),
        ),
    ),
    ('Osun',(
        ('85','Osun East'),
        ('86','Osun Central'),
        ('87','Osun West'),
        ),
    ),
    ('Oyo',(
        ('88','Oyo South'),
        ('89','Oyo Central'),
        ('90','Oyo North'),
        ),
    ),
    ('Plateau',(
        ('91','Plateau South'),
        ('92','Plateau Central'),
        ('93','Plateau North'),
        ),
    ),
    ('Rivers',(
        ('94','Rivers East'),
        ('95','Rivers South-East'),
        ('96','Rivers West'),
        ),
    ),
    ('Sokoto',(
        ('97','Sokoto South'),
        ('98','Sokoto East'),
        ('99','Sokoto North'),
        ),
    ),
    ('Taraba',(
        ('100','Taraba South'),
        ('101','Taraba Central'),
        ('102','Taraba North'),
        ),
    ),
    ('Yobe',(
        ('103','Yobe South'),
        ('104','Yobe East'),
        ('105','Yobe North'),
        ),
    ),
    ('Zamfara',(
        ('106','Zamfara West'),
        ('107','Zamfara Central'),
        ('108','Zamfara North'),
        ),
    ),
    ('FCT',(
        ('109','Federal Capital Territory'),
        ),
    ),
)