



NIG_STATE_CONSTITUENCIES= (
    
    ('Abia',(
        ('1', 'Aba North'),
        ('2','Aba South'),
        ('3','Aba Central'),
        ('4', 'Arochukwu'),
        ('5', 'Bende North'),
        ('6', 'Bende South'),
        ('7', 'Ikwuano'),
        ('8', 'Isiala Ngwa North'),
        ('9', 'Isiala Ngwa South'),
        ('10', 'Isuikwuato'),
        ('11', 'Obingwa East'),
        ('12', 'Obingwa West'),
        ('13', 'Ohafia North'),
        ('14', 'Ohafia South'),
        ('15', 'Osisioma North'),
        ('16', 'Osisioma South'),
        ('17', 'Umunneochi'),
        ('18', 'Ugwuna Agbo'),
        ('19','Ukwa East'),
        ('20', 'Ukwa West'),
        ('21', 'Umuahia East'),
        ('22', 'Umuahia West'),
        ('23', 'Umuahia Central'),
        ('24', 'Umuahia South'),
        ),
    ),
    
    ('Edo',(
        ('25','Akoko-Edo I'),
        ('26','Akoko-Edo II'),
        ('27','Esan Central'),
        ('28', 'Esan West'),
        ('29', 'Esan North East I'),
        ('30', 'Esan North East II'),
        ('31', 'Esan South East'),
        ('32', 'Etsako Central'),
        ('33', 'Etsako East'),
        ('34', 'Etsako West I'),
        ('35', 'Etsako West II'),
        ('36', 'Egor'),
        ('37', 'Ikpoba-Okha'),
        ('38', 'Igueben'),
        ('39', 'Oredo East'),
        ('40', 'Oredo West'),
        ('41', 'Orhionmwon I'),
        ('42', 'Orhionmwon II'),
        ('43', 'Ovia North East I'),
        ('44', 'Ovia North East II'),
        ('45', 'Ovia South West'),
        ('46', 'Owan East'),
        ('47', 'Owan West'),
        ('48', 'Uhunmwode'),
        ),
    ),
    ('Lagos',(
        ('49', 'Alimosho I'),
        ('50', 'Alimosho II'),
        ('51', 'Ojo I'),
        ('52', 'Ojo II'),
        ('53', 'Badagry I'),
        ('54', 'Badagry II'),
        ('55', 'Epe I'),
        ('56', 'Epe II'),
        ('57', 'Agege I'),
        ('58', 'Agege II'),
        ('59','Ifako-Ijaiye I'),
        ('60','Ifako-Ijaiye II'),
        ('61','Oshodi-Isolo I'),
        ('62','Oshodi-Isolo II'),
        ('63','Ibeju Lekki I'),
        ('64','Ibeju Lekki II'),
        ('65','Eti-Osa I'),
        ('66','Eti-Osa II'),
        ('67','Apapa I'),
        ('68','Apapa II'),
        ('69', 'Ikeja I'),
        ('70', 'Ikeja II'),
        ('71','Ikorodu I'),
        ('72','Ikorodu II'),
        ('73','Lagos Island I'),
        ('74', 'Lagos Island II'),
        ('75','Lagos Mainland I'),
        ('76','Lagos Mainland II'),
        ('77','Amuwo-Odofin I'),
        ('78','Amuwo-Odofin II'),
        ('79','Ajeromi-Ifelodun I'),
        ('80','Ajeromi-Ifelodun II'),
        ('81','Shomolu I'),
        ('82','Shomolu II'),
        ('83','Kosofe I'),
        ('84','Kosofe II'),
        ('85','Surulere I'),
        ('86','Surulere II'),
        ),
    ),
    # Kebbi
    ('Kogi',(
        ('87', 'Adavi'),
        ('88','Ajaokuta'),
        ('89','Ankpa I'),
        ('90','Ankpa II'),
        ('91','Bassa'),
        ('92','Dekina/Biraidu'),
        ('93','Okura'),
        ('94','Ibaji'),
        ('95','Idah'),
        ('96','Igalamela-Odolu'),
        ('97','Ijumu'),
        ('98','Kabba/Bunu'),
        ('99','Kogi(K.K)'),
        ('100','Lokoja I'),
        ('101','Lokoja II'),
        ('102','Mopamuro'),
        ('103','Ofu'),
        ('104','Ogori/Magonro'),
        ('105','Okehi'),
        ('106','Okene Town'),
        ('107','Okene II (South)'),
        ('108','Olamaboro'),
        ('109','Omala'),
        ('110','Yagba East'),
        ('111','Yagba West'),
        ),
    ),
    
)
    
 

