from django.contrib import admin
from .models import *
admin.site.register(PartyManifestoe)
admin.site.register(PartyManifestoeDetail)
admin.site.register(Politician)
admin.site.register(PoliticalParty)
admin.site.register(Presidency)
admin.site.register(Guber)
admin.site.register(Senate)
admin.site.register(Fed_Rep)
admin.site.register(Chairmanship)
admin.site.register(State_Rep)
admin.site.register(Councilorship)
admin.site.register(Presidential)
admin.site.register(Gubernatorial)
admin.site.register(Senatorial)
admin.site.register(CandidateManifestoe)
admin.site.register(CandidateManifestoeDetail)
admin.site.register(Fed_House)
admin.site.register(LGAChairmanship)
admin.site.register(State_House)
admin.site.register(WardCouncilorship)